apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
  labels:
    app: iris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris-api
        image: IMAGE_PLACEHOLDER # This placeholder will be replaced by the workflow
        ports:
        - containerPort: 80 # This is the only port definition needed here
