name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: fourth-scheme-461516-n2
  GAR_LOCATION: us-central1
  REPO_NAME: repo
  IMAGE_NAME: iris-api
  CLUSTER_NAME: gke-cluster-iris
  CLUSTER_ZONE: us-west1
  DEPLOYMENT_NAME: iris-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # The 'google-github-actions/auth' action is now replaced by your manual steps.
    # The gcloud CLI needs to be set up first.
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    # Your new manual authentication step
    - name: Authenticate to Google Cloud
      env:
        GCP_CREDENTIALS_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}
      run: |
        # Decode the Base64 secret and create the service account key file
        echo "$GCP_CREDENTIALS_B64" | base64 -d > gcp-key.json
        
        # Authenticate with gcloud using the key file
        gcloud auth activate-service-account --key-file=gcp-key.json
        
        # Set the project for all subsequent gcloud commands
        gcloud config set project ${{ env.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ env.IMAGE_NAME }} ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Get GKE cluster credentials
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }}

    - name: Deploy to GKE with kubectl
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.IMAGE_NAME }}=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
